### ISSUE TITLE
neovim: tabs with different projects selected

### ISSUE THREAD

**Issue by rakesh-mth** [benwainwright/fzf-project#15]
Steps to repro:

Open tab and switch to a project
Open another tab and switch to a different project
switch back to previous tab and run GFiles
It finds files from project selected in 2nd tab.

To resolve this issue, had to change execute command in fzfproject#changeDir from

  call fzfproject#execute('cd', fnameescape(a:dir), a:context)

to

  call fzfproject#execute('lcd', fnameescape(a:dir), a:context)

Do you have any other recommendation to resolve this ? Please let me know if I can create a PR.

**Comment by benwainwright** [comment]
Thanks for raising the issue!

There was actually a general bug in the autorooting behaviour that I'd missed (not just for tabs). Should be fixed now. Please reopen if it isn't!

**Comment by rakesh-mth** [comment]
I still have same issue after upgrading this plugin. Could you please try reproduce using above steps ?

**Comment by benwainwrightcinch** [comment]
@rakesh-mth sorry! In fixing a different bug I introduced a regression in this behaviour :( need to find a way of integration testing vim plugins!

Try now, I think I've fixed it.

**Comment by rakesh-mth** [comment]
It is still not working for me after update. Thanks for looking into this issue.

**Comment by benwainwrightcinch** [comment]
Yeah I know why @rakesh-mth I'm looking into it. Its because of this: https://github.com/junegunn/fzf/blob/master/plugin/fzf.vim#L590-L604

**Comment by benwainwrightcinch** [comment]
@rakesh-mth try now

**Comment by rakesh-mth** [comment]
After update I am getting below error by just running nvim:

Error detected while processing function fzfproject#autoroot#doroot[14]..fzfproject#autoroot#doroot[14]..fzfproject#autoroot#doroot
[14]..fzfproject#autoroot#doroot[14]..fzfproject#autoroot#doroot[14]..

line   14:
E132: Function call depth is higher than 'maxfuncdepth'

**Comment by rakesh-mth** [comment]
Original issue is fixed now, but I see above error on switching tabs and on first start of neovim.

**Comment by benwainwrightcinch** [comment]
@rakesh-mth I can't replicate. I was getting that bug before but I fixed it on my end; what system are you on?

**Comment by benwainwrightcinch** [comment]
@rakesh-mth I've made a change. See if your problem is fixed now.

**Comment by rakesh-mth** [comment]
Looks good now. Thank You!

**Comment by benwainwright** [comment]
@rakesh-mth no problem! Sorry for the back and forth. Definitely the next thing I'm going to do is work out how to add automatic testing into this codebase 🙄

**Comment by rakesh-mth** [comment]
@benwainwright Thanks for your help on this issue. I switched to windows and new changes did not work, I had to make some changes to get project selection working. Change is part of this PR [#17 ](https://github.com/benwainwright/fzf-project/pull/17). This issue (#15) is not fixed on windows even after my change. Need your help on this since I may not able to figure it out.

**Comment by benwainwright** [comment]
@rakesh-mth I don't own a windows machine so I'm unable to support windows I'm afraid. Happy to accept windows related PRs, but you are on your own on this front. Sorry!
